version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: supp_nginx
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8080:80"
    depends_on:
      - app

  app:
    build:
      args:
        user: sassr
        uid: 1000
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: supp_app
    volumes:
      - ./:/var/www
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: supp_db
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_USER: ${DB_USERNAME}
        MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci